drop view if exists public.popular_tags_view;
DROP TABLE IF EXISTS Partis_Politiques, Tags, Sources, personnalites, declarations, actualites, declarations_tags;


CREATE TABLE Partis_Politiques (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
               nom varchar UNIQUE,
               nom_court varchar UNIQUE,
               color varchar,
               "order" int,
               created_on timestamp,
               updated_on timestamp, created_by varchar, last_modified_by varchar);

CREATE TABLE Tags (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, nom varchar UNIQUE, color varchar, "order" int, created_on timestamp,
                   updated_on timestamp, created_by varchar, last_modified_by varchar);

CREATE TABLE Sources (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, nom varchar UNIQUE, color varchar, "order" int, created_on timestamp,
                      updated_on timestamp, created_by varchar, last_modified_by varchar);

CREATE TABLE personnalites (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    prenom varchar,
    nom varchar,
    parti_politique_id int REFERENCES partis_politiques (id) ON DELETE SET NULL,
    ville varchar,
    departement varchar,
    region varchar,
    fonction varchar,
    extra_infos json,
    created_on timestamp,
    updated_on timestamp,
    created_by varchar,
    last_modified_by varchar,
    UNIQUE (nom, prenom)
);

create table declarations (

  citation text null,
  date date null,
  source_id integer null REFERENCES sources (id) ON DELETE SET NULL,
  lien varchar null,
  collecteur varchar null,
  commentaire text null,
  est_publie boolean null,
  personnalite_id integer null REFERENCES personnalites (id) ON DELETE SET NULL,
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_on timestamp without time zone null,
  updated_on timestamp without time zone null,
  created_by text null,
  last_modified_by text null
);

create table actualites (
    texte text null,
    est_publie boolean null,
    date date null,
    source_id integer null REFERENCES sources (id) ON DELETE SET NULL,
    lien varchar null,
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_on timestamp,
    updated_on timestamp,
    created_by varchar null,
    last_modified_by varchar null
);

CREATE TABLE declarations_tags (
    declaration_id int REFERENCES declarations (id) ON UPDATE CASCADE ON DELETE CASCADE,
    tag_id int REFERENCES tags (id) ON UPDATE CASCADE ON DELETE CASCADE,
    created_on timestamp,
    CONSTRAINT declaration_tag_pkey PRIMARY KEY (declaration_id, tag_id)
);

create view public.popular_tags_view as
select
  t.id,
  t.nom as name,
  count(dt.declaration_id) as quotes_count
from
  tags t
  join declarations_tags dt on dt.tag_id = t.id
group by
  t.id
order by
  (count(dt.declaration_id)) desc;

/*
create view public.personnalites_view as
select
  p.id,
  concat(p.prenom, ' ', p.nom) as nom_complet,
  p.parti_politique_id,
  pp.nom as parti_politique,
  p.fonction,
  p.ville,
  p.departement,
  p.region
from
  personnalites p
  left join partis_politiques pp on pp.id = p.parti_politique_id;
 */
